give  Sun 12 Jul 19:55:51 AEST 2020: passing all of checkout's autotests

diff --git a/shrug-add b/shrug-add
--- a/shrug-add
+++ b/shrug-add
@@ -6,6 +6,19 @@
 # Checks if the repo exists
 . shrug-exists
 
+# First check if all the supplied filenames exist in the current directory or index
+# TODO: Extract this out? Same thing in shrug-add
+for eachFile in "$@"; do
+    if ! test -e "$eachFile"; then
+        if ! test -e "$stageDir/$eachFile"; then
+            echo "$thisFile: error: can not open '$eachFile'"
+            exit 1
+        else
+            continue
+        fi
+    fi
+done
+
 for eachFile in "$@"; do
     if test -e "$eachFile"; then
         # Target file already exists - ie. it was staged already
@@ -29,3 +42,6 @@ for eachFile in "$@"; do
         fi
     fi
 done
+
+
+
diff --git a/shrug-rm b/shrug-rm
--- a/shrug-rm
+++ b/shrug-rm
@@ -30,6 +30,17 @@ if test $# -le 0; then
     exit 1
 fi
 
+# First check if all the supplied filenames exist in the current directory or index
+# TODO: Extract this out?
+for eachFile in "$@"; do
+    if ! test -e "$stageDir/$eachFile"; then
+        echo "$thisFile: error: '$eachFile' is not in the shrug repository"
+        exit 1
+    else
+        continue
+    fi
+done
+
 stageFiles=$(ls $stageDir)
 cwdFiles=$(ls $cwd)
 headFiles=$(ls $headDir)
