give  Sun 12 Jul 18:31:23 AEST 2020: passing 3 in subset 2

diff --git a/shrug-add b/shrug-add
--- a/shrug-add
+++ b/shrug-add
@@ -1,38 +1,31 @@
 #!/bin/dash
+# Stages the target files in the repo index
 
-repoName=".shrug"
-stageDir="$repoName/index"
-
-# Check if the repo exists
-if ! test -e "$repoName"; then
-    echo "$0: error: no $repoName directory containing shrug repository exists"
-    exit 1
-fi
-
-# Creating the index directory if it doesn't exist
-if ! test -e "$stageDir"; then
-    mkdir "$stageDir"
-fi
+# Initialises variables used in this script
+. shrug-conf
+# Checks if the repo exists
+. shrug-exists
 
 for eachFile in "$@"; do
     if test -e "$eachFile"; then
-        # echo " ===> Adding: $eachFile"
-
-        # The filename already exists - ie. it was staged already.
-        # if test -e "$stageDir/$eachFile"; then
-            # echo "     ---> $eachFile already staged. Overwriting"
-        # fi
-
+        # Target file already exists - ie. it was staged already
+        # cp overwrites the existing staged file by default
         cp "$eachFile" "$stageDir"
     else
-        # Specified file does not exist in the current directory
-        # If it exists in the index, then it was probably deleted
-        if test -e "$stageDir/$eachFile"; then
+        # Target file does not exist in the current directory.
+        if test -e "$stageDir/$eachFile"; then  
+            # If it exists in the index however, then it was probably from the cwd
+            # Proceed to remove the target from the index
             rm "$stageDir/$eachFile"
         else 
-            echo "$0: error: can not open '$eachFile'"
+            if ! sh shrug-validname "$eachFile"; then
+                # Check that the filename is valid
+                echo "$thisFile: error: invalid filename '$eachFile'"
+                exit 1
+            else 
+                echo "$thisFile: error: can not open '$eachFile'"
+                exit 1
+            fi
         fi
-        exit 1
     fi
 done
-
diff --git a/shrug-branch b/shrug-branch
--- a/shrug-branch
+++ b/shrug-branch
@@ -1,17 +1,16 @@
 #!/bin/dash
 
-repoName=".shrug"
-currBranch="current-branch"
+. shrug-conf
 
 # No shrug directory
 if ! test -e $repoName; then
-    echo "$0: error: no .shrug directory containing shrug repository exists"
+    echo "$thisFile: error: no .shrug directory containing shrug repository exists"
     exit 1
 fi
 
 # If no commits, don't allow the use of branches
 if ! sh get-head > /dev/null; then
-    echo "$0: error: your repository does not have any commits yet"
+    echo "$thisFile: error: your repository does not have any commits yet"
     exit 1
 fi
 
@@ -22,37 +21,59 @@ if test $# = 0; then
 elif test $# -eq 1; then
     if test $1 = "-d"; then
         # Only -d was supplied
-        echo "$0: error: branch name required"
+        echo "$thisFile: error: branch name required"
         exit 1
     else
         # Treating first argument as the new branch name
         # Check for invalid branch name
         branchName=$1
-        if sh validname $branchName > /dev/null; then
+        if sh shrug-validname $branchName > /dev/null; then
             newBranch="$repoName/$branchName"
             if test -e $newBranch; then
-                echo "$0: error: branch '$newBranch' already exists"
+                echo "$thisFile: error: branch '$branchName' already exists"
                 exit 1
             fi
 
             # Creating a new branch
             mkdir "$newBranch"
             # Copy over all files over the new branch directory?
-            cp $(ls) "$newBranch" 2> /dev/null
-
+            cd "$repoName/$currBranch"  # TODO: bad style
+            cp $(ls) "../$branchName"  
+            cd ../../
+            # Copy over the log file, if it exists
+            if test -e $logFile; then
+                cat $logFile > "$newBranch/.log" 
+            fi
         else
-            echo "$0: error: invalid branch name '$branchName'"
+            echo "$thisFile: error: invalid branch name '$branchName'"
         fi
     fi
 elif test $# -eq 2; then
     if test $1 = "-d"; then
         branchName=$2
-        if sh validname $branchName; then
-            echo Deleting branch $branchName
+        if sh shrug-validname $branchName; then
+            # Target branch doesn't exist
+            branchDir="$repoName/$branchName"
+            if ! test -e $branchDir; then
+                echo "$thisFile: error: branch '$branchName' does not exist"
+                exit 1
+            fi
+            # Can't delete the target branch if it's the current branch OR if it's the master branch
+            if test $branchName = $master; then
+                echo "$thisFile: error: can not delete branch '$master'"
+                exit 1
+            elif test "$(readlink $repoName/$currBranch)" = $branchName; then
+                echo "$thisFile: error: can't delete the current branch you're on"
+                exit 1
+            fi
+            # Deleting the branch
+            echo "Deleted branch '$branchName'"
+            rm -r "$branchDir"
+            # TODO: check for unmerged work 
         else
-            echo "$0: error: invalid branch name '$branchName'"
+            echo "$thisFile: error: invalid branch name '$branchName'"
         fi        
     else
-        echo "usage: $0 [-d] <branch>"
+        echo "usage: $thisFile [-d] <branch>"
     fi
 fi
diff --git a/shrug-checkout b/shrug-checkout
--- a/shrug-checkout
+++ b/shrug-checkout
@@ -1,20 +1,75 @@
 #!/bin/dash
 
-repoName=".shrug"
-stageDir="$repoName/index"
-currBranch="current-branch"
+. shrug-conf
+. shrug-exists
+
 branchName=$1
 branchDir="$repoName/$branchName"
 
-cd "$repoName" # TODO: is this robust enough?
+cd "$repoName"
 
 if test "$(readlink $currBranch)" = $branchName; then
+    # If current-branch is already pointing to the target branch, do nothing
     echo "Already on '$branchName'"
     exit 0
 else
-    echo "Switched to branch '$branchName'"
-    ln -sfn "$branchName" "$currBranch"
+    # If the branch doesn't exist, we can't checkout to it
+    if ! test -e $branchName; then
+        echo "$thisFile: error: unknown branch '$branchName'"
+        exit 1
+    fi
+    # TODO: User needs to commit their changes before checking out
 
-    # Remove everything in cwd
-    cp $currBranch/* ../new
+    stageFiles=$(ls $stage)
+    cwdFiles=$(ls ../)
+    branchFiles=$(ls $branchName)
+    # echo "===== Stage Files   ====="
+    # echo "$stageFiles"
+    # echo "===== CWD Files     ====="
+    # echo "$cwdFiles"
+    # echo "===== Branch Files  ====="
+    # echo "$branchFiles"
+
+
+
+    cd ..
+    for eachFile in $(echo $stageFiles $cwdFiles $branchFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
+        if test -e "$repoName/$branchName/$eachFile"; then
+            if ! shrug-file-should-commit $eachFile  > /dev/null; then
+                # echo " ===> REPLACING FILE $eachFile"
+                rm "$eachFile" 2> /dev/null
+                rm "$stageDir/$eachFile" 2> /dev/null
+                cp "$repoName/$branchName/$eachFile" "$eachFile"
+                cp "$repoName/$branchName/$eachFile" "$stageDir/$eachFile"
+            fi  
+        else
+            if ! shrug-file-should-commit $eachFile > /dev/null; then
+                # echo " ===> DELETING FILE $eachFile"
+                rm "$eachFile"
+                rm "$stageDir/$eachFile"
+            fi  
+        fi
+    done
+    cd $repoName
+
+    ln -sfn "$branchName" "$currBranch"
+    echo "Switched to branch '$branchName'"
 fi
+
+
+    # # Remove every file inside the cwd AND the index which is in the current branch
+    # for eachFile in $(ls $currBranch); do
+    #     # echo "Wiping $eachFile from CWD and index"
+    #     rm "../$eachFile"
+    #     rm "$stage/$eachFile"
+    # done
+
+    # ln -sfn "$branchName" "$currBranch"
+    # echo "Switched to branch '$branchName'"
+
+    # # Copy every file inside the current branch into the cwd AND the index
+    # for eachFile in $(ls $currBranch); do
+    #     # echo "Fetching $eachFile to CWD"
+    #     cp "${currBranch}/${eachFile}" "../$eachFile"
+    #     cp "${currBranch}/${eachFile}" "$stage/$eachFile"
+    # done
diff --git a/shrug-init b/shrug-init
--- a/shrug-init
+++ b/shrug-init
@@ -1,19 +1,25 @@
 #!/bin/dash
+# Creates the repo, an empty master branch and an empty index
 
-thisFilename=$(basename "$0")
-repoName=".shrug"
-master="master"
-currBranch="current-branch"
+# Initialises variables used in this script
+. shrug-conf
 
+# Creating the repo subdirectory
 if mkdir "$repoName" 2> /dev/null; then
-    # Creating a master branch
+    # Creating the index directory if it doesn't exist
+    if ! test -e "$stageDir"; then
+        mkdir "$stageDir"
+    fi
+    
+    # Creating an empty master branch under the repo subdirectory 
+    # and set it as the current branch (by symlink)
     masterBranch="$repoName/$master"
     mkdir "$masterBranch"
-    # TODO: Push everything in cwd to master branch?
-    cp $(ls) $masterBranch 2> /dev/null  # TODO: Add -r?
-    cd "$repoName"  # TODO: not safe?
+    cd "$repoName"
     ln -sfn "$master" "$currBranch"
+    cd ..
+    
     echo "Initialized empty shrug repository in .shrug"
 else 
-    echo "$thisFilename: error: $repoName already exists"
+    echo "$thisFile: error: $repoName already exists"
 fi
diff --git a/shrug-rm b/shrug-rm
--- a/shrug-rm
+++ b/shrug-rm
@@ -1,15 +1,12 @@
 #!/bin/dash
 
-repoName=".shrug"
-stageDir="$repoName/index"
-cwd=$(pwd)  # TODO: Pwd won't work if run in diff directory...
-latestCommit=$(sh get-head)
-headDir="$repoName/$latestCommit"
+. shrug-conf
+cwd=$(pwd) 
 
 default=true
 force=false
 cached=false
-while test $# -gt 0; do  # $# is the number of args
+while test $# -gt 0; do
     case "$1" in
         --force) 
             default=false
@@ -29,11 +26,9 @@ while test $# -gt 0; do  # $# is the number of args
 done
 
 if test $# -le 0; then
-    echo "usage: $0 [--force] [--cached] <filenames>"
+    echo "usage: $thisFile [--force] [--cached] <filenames>"
     exit 1
 fi
-
-# echo "Filenames: $@"
 
 stageFiles=$(ls $stageDir)
 cwdFiles=$(ls $cwd)
@@ -43,10 +38,11 @@ for eachFile in "$@"; do
     stageFile="$stageDir/$eachFile"
     headFile="$headDir/$eachFile"
     currFile="$cwd/$eachFile"
-    # TODO: catch invalid filenames
-    # echo $currFile
-    # echo $stageFile
-    # echo $headFile
+    # Check that the filename is valid
+    if ! sh shrug-validname "$eachFile"; then
+        echo "$thisFile: error: invalid filename '$eachFile'"
+        exit 1
+    fi
 
     # All files exist
     if test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
@@ -55,13 +51,13 @@ for eachFile in "$@"; do
                 if test -z "$(diff $stageFile $headFile)"; then
                     rm $currFile $stageFile
                 else 
-                    echo "$0: error: '$eachFile' has changes staged in the index"
+                    echo "$thisFile: error: '$eachFile' has changes staged in the index"
                 fi
             else
                 if test -z "$(diff $stageFile $headFile)"; then
-                    echo "$0: error: '$eachFile' in repository is different to working file"
+                    echo "$thisFile: error: '$eachFile' in repository is different to working file"
                 else 
-                    echo "$0: error: '$eachFile' in index is different to both working file and repository"
+                    echo "$thisFile: error: '$eachFile' in index is different to both working file and repository"
                 fi
             fi
         elif test $cached = true && test $force = true; then
@@ -77,7 +73,7 @@ for eachFile in "$@"; do
                 if test -z "$(diff $stageFile $headFile)"; then
                     rm $stageFile
                 else 
-                    echo "$0: error: '$eachFile' in index is different to both working file and repository"
+                    echo "$thisFile: error: '$eachFile' in index is different to both working file and repository"
                 fi
             fi
         elif test $force = true; then 
@@ -87,9 +83,9 @@ for eachFile in "$@"; do
     elif test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
         if test $default = true; then
             if test -z "$(diff $currFile $stageFile)"; then
-                echo "$0: error: '$eachFile' has changes staged in the index"
+                echo "$thisFile: error: '$eachFile' has changes staged in the index"
             else
-                echo "$0: error: '$eachFile' in index is different to both working file and repository"
+                echo "$thisFile: error: '$eachFile' in index is different to both working file and repository"
             fi
         elif test $cached = true && test $force = true; then
             rm "$stageFile"
@@ -98,29 +94,29 @@ for eachFile in "$@"; do
                 rm "$stageFile"
             else
                 rm $stageFile
-                echo "$0: error: '$eachFile' in index is different to both working file and repository"
+                echo "$thisFile: error: '$eachFile' in index is different to both working file and repository"
             fi
         elif test $force = true; then 
             rm "$stageFile" "$currFile"
         fi
     elif test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
-        echo "$0: error: '$eachFile' is not in the shrug repository"
+        echo "$thisFile: error: '$eachFile' is not in the shrug repository"
         exit 0
     elif ! test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
         rm $stageFile
         exit 0
     # Two files missing
     elif test -e "$currFile" && ! test -e "$stageFile" && ! test -e "$headFile"; then
-        echo "$0: error: '$eachFile' is not in the shrug repository"
+        echo "$thisFile: error: '$eachFile' is not in the shrug repository"
         exit 0
     elif ! test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
         rm $stageFile
         exit 0
     elif ! test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
-        echo "$0: error: '$eachFile' is not in the shrug repository"
+        echo "$thisFile: error: '$eachFile' is not in the shrug repository"
         exit 0
     elif ! test -e "$currFile" && ! test -e "$stageFile" && ! test -e "$headFile"; then
-        echo "$0: error: '$eachFile' is not in the shrug repository"
+        echo "$thisFile: error: '$eachFile' is not in the shrug repository"
         exit 0
     fi
 done
diff --git a/shrug-show b/shrug-show
--- a/shrug-show
+++ b/shrug-show
@@ -1,24 +1,11 @@
 #!/bin/dash
 
-# Variables
-repoName=".shrug"
-stageDir="index"
-
-# Check if the repo exists (TODO? Is this right? this fails the autotest but I swear the reference does this)
-# if ! test -e "$repoName"; then
-#     echo "$0: error: no .shrug directory containing shrug repository exists"
-#     exit 1
-# fi
-
-# No commits in the repo (TODO?)
-# if ! sh get-head > /dev/null; then
-# 	echo "$0: error: your repository does not have any commits yet"
-# 	exit 1
-# fi
+. shrug-conf
+. shrug-exists
 
 # Incorrect usage
 if test "$#" -ne 1; then
-  echo "usage: $0 <commit>:<filename>"
+  echo "usage: $thisFile <commit>:<filename>"
   exit 1
 fi
 
@@ -27,30 +14,31 @@ fileToShow=$(echo $1 | cut -d':' -f2 -s)
 
 if test -z "$commitNum" && test -z "$fileToShow"; then
 	# No colon inside the supplied argument
-	echo "$0: error: invalid object $1"	
+	echo "$thisFile: error: invalid object $1"	
 	exit 1
-elif ! sh validname "$fileToShow"; then
-	echo "$0: error: invalid filename '$fileToShow'"
+elif ! sh shrug-validname "$fileToShow" 2> /dev/null; then
+	echo "$thisFile: error: invalid filename '$fileToShow'"
 	exit 1
 fi
 
 commitDir=""
 if test -z "$commitNum"; then
-	# No commit number/hash specified. Using index
-	commitDir="$repoName/$stageDir"
-	if ! test -e "$commitDir/$fileToShow"; then
-		echo "$0: error: '$fileToShow' not found in $stageDir"
+	# No commit number/hash specified. Showing file from the index
+	commitDir="$stageDir"
+	if ! test -e "$stageDir/$fileToShow"; then
+		# File to show doesn't exist in the index
+		echo "$thisFile: error: '$fileToShow' not found in $stage"
 		exit 1
 	fi
 else 
 	commitDir="$repoName/$commitNum"
 	if ! test -e "$commitDir"; then
-		echo "$0: error: unknown commit '$commitNum'"
+		# Specified commit doesn't exist
+		echo "$thisFile: error: unknown commit '$commitNum'"
 		exit 1 
 	fi
-
 	if ! test -e "$commitDir/$fileToShow"; then
-		echo "$0: error: '$fileToShow' not found in commit $commitNum"
+		echo "$thisFile: error: '$fileToShow' not found in commit $commitNum"
 		exit 1
 	fi
 fi
diff --git a/shrug-status b/shrug-status
--- a/shrug-status
+++ b/shrug-status
@@ -1,28 +1,18 @@
 #!/bin/dash
 
-repoName=".shrug"
-stageDir="$repoName/index"
+. shrug-conf
 cwd=$(pwd)
-latestCommit=$(sh get-head)
-headDir="$repoName/$latestCommit"
 
-# Creating the index directory if it doesn't exist (should this be done?)
-if ! test -e "$stageDir"; then
-    mkdir "$stageDir"
+# Check if the repository has any commits
+if ! sh get-head > /dev/null; then
+    echo "$thisFile: error: your repository does not have any commits yet"
     exit 1
 fi
-
-# Check if the repository has any commits (TODO is this right?)
-# if ! sh get-head; then
-#     echo "$0: error: your repository does not have any commits yet"
-#     exit 1
-# fi
 
 stageFiles=$(ls $stageDir)
 cwdFiles=$(ls $cwd)
 headFiles=$(ls $headDir)
 
-# TODO: String set?
 for eachFile in $(echo $stageFiles $cwdFiles $headFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
     stageFile="$stageDir/$eachFile"
     headFile="$headDir/$eachFile"
@@ -30,7 +20,6 @@ for eachFile in $(echo $stageFiles $cwdFiles $headFiles | tr " " "\n" | sort | u
     # TODO: catch invalid filenames
 
     # All files exist
-    # TODO FIX THIS
     if test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
         if test -z "$(diff $currFile $stageFile)"; then
             if test -z "$(diff $stageFile $headFile)"; then
