give  Mon  6 Jul 12:16:52 AEST 2020: fixed log file writing and started shrug-show

diff --git a/shrug-commit b/shrug-commit
--- a/shrug-commit
+++ b/shrug-commit
@@ -1,5 +1,38 @@
 #!/bin/dash
 
+# Variables:
+repoName=".shrug"
+stageDir="$repoName/index"
+commitNum=0
+commitDir="$repoName/$commitNum"
+logFile="$repoName/.log"
+
+# Check if the repo exists
+if ! test -e "$repoName"; then
+    echo "$0: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi
+
+# Creating the index directory if it doesn't exist (should this be done?)
+if ! test -e "$stageDir"; then
+    mkdir "$stageDir"
+    echo "nothing to commit"
+    exit 1
+fi
+
+# Check if the index/staging area is empty (Should I do this? NOT ROBUST either?)
+if test -z "$(ls "${stageDir}")"; then
+    echo "nothing to commit"
+    exit 1
+fi
+
+# Check if the stage contains additional files/modifications that need to be
+# committed to a new snapshot by comparing with the latest commit
+if ! sh should-commit $repoName/$(sh get-head) "$stageDir" > /dev/null; then
+    echo "nothing to commit"
+    exit 1
+fi
+
 while test $# -gt 0; do  # $# is the number of args
     case "$1" in
         -a) 
@@ -10,21 +43,18 @@ while test $# -gt 0; do  # $# is the number of args
             # Extract the commit message
             shift
             message=$1
+            if test -z "$message"; then
+                echo "usage: $0 [-a] -m commit-message"
+                exit 1
+            fi
             shift
             ;;
         *)
-            echo usage: shrug-commit [-a] -m commit-message
+            "echo usage: $0 [-a] -m commit-message"
             exit 1
             ;;
     esac
 done
-
-# Variables:
-repoName=".shrug"
-stageDir="$repoName/index"
-commitNum=0
-commitDir="$repoName/$commitNum"
-logFile="$repoName/.log"
 
 while test -e "$commitDir"; do
     commitNum=$(expr $commitNum + 1)
@@ -33,12 +63,6 @@ done
 
 # Creating a snapshot folder
 mkdir "$commitDir" || exit 1
-
-# Check if the index/staging area is empty (NOT ROBUST?)
-if test -z "$(ls "${stageDir}")"; then
-    echo "nothing to commit"
-    exit 1
-fi
 
 # For each file in the index/staging area, copy each into the snapshot folder
 for eachFile in $(ls "${stageDir}"); do
diff --git a/shrug-show b/shrug-show
--- a/shrug-show
+++ b/shrug-show
@@ -1,10 +1,18 @@
 #!/bin/dash
 
+# Variables
 repoName=".shrug"
 stageDir="index"
 
+# Check if the repo exists
+if ! test -e "$repoName"; then
+    echo "$0: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi
+
+
 # No commits in the repo
-if ! ./shrug-head > /dev/null; then
+if ! sh get-head > /dev/null; then
 	echo "$0: error: your repository does not have any commits yet"
 	exit 1
 fi
@@ -22,7 +30,7 @@ if test -z "$commitNum" && test -z "$fileToShow"; then
 	# No colon inside the supplied argument
 	echo "$0: error: invalid object $1"	
 	exit 1
-elif ! ./validname "$fileToShow"; then
+elif ! sh validname "$fileToShow"; then
 	echo "$0: error: invalid filename '$fileToShow'"
 	exit 1
 fi
@@ -31,16 +39,21 @@ commitDir=""
 if test -z "$commitNum"; then
 	# No commit number/hash specified. Using index
 	commitDir="$repoName/$stageDir"
+	if ! test -e "$commitDir/$fileToShow"; then
+		echo "$0: error: '$fileToShow' not found in $stageDir"
+		exit 1
+	fi
 else 
 	commitDir="$repoName/$commitNum"
-fi
+	if ! test -e "$commitDir"; then
+		echo "$0: error: unknown commit '$commitNum'"
+		exit 1 
+	fi
 
-# echo " ===> Commit direc: $commitDir"
-# echo " ===> File to show: $fileToShow"
-
-if ! test -e "$commitDir/$fileToShow"; then
-	echo "$0: error: '$fileToShow' not found in $commitDir"
-	exit 1
+	if ! test -e "$commitDir/$fileToShow"; then
+		echo "$0: error: '$fileToShow' not found in commit $commitNum"
+		exit 1
+	fi
 fi
 
 cat "$commitDir/$fileToShow"
