give  Mon  6 Jul 10:44:32 AEST 2020: fixed log file writing and started shrug-show

diff --git a/shrug-log b/shrug-log
--- a/shrug-log
+++ b/shrug-log
@@ -3,8 +3,14 @@
 repoName=".shrug"
 logFile="$repoName/.log"
 
+if ! test -e "$repoName"; then
+    echo "$0: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi
+
+if ! test -e "$logFile"; then
+    echo "$0: error: your repository does not have any commits yet"
+    exit 1
+fi
+
 cat "$logFile"
-
-
-
-
diff --git a/shrug-show b/shrug-show
--- a/shrug-show
+++ b/shrug-show
@@ -1,7 +1,46 @@
 #!/bin/dash
 
-echo "===== Shrug Show ====="
+repoName=".shrug"
+stageDir="index"
 
+# No commits in the repo
+if ! ./shrug-head > /dev/null; then
+	echo "$0: error: your repository does not have any commits yet"
+	exit 1
+fi
 
+# Incorrect usage
+if test "$#" -ne 1; then
+  echo "usage: $0 <commit>:<filename>"
+  exit 1
+fi
 
-echo "======================"
+commitNum=$(echo $1 | cut -d':' -f1 -s)
+fileToShow=$(echo $1 | cut -d':' -f2 -s)
+
+if test -z "$commitNum" && test -z "$fileToShow"; then
+	# No colon inside the supplied argument
+	echo "$0: error: invalid object $1"	
+	exit 1
+elif ! ./validname "$fileToShow"; then
+	echo "$0: error: invalid filename '$fileToShow'"
+	exit 1
+fi
+
+commitDir=""
+if test -z "$commitNum"; then
+	# No commit number/hash specified. Using index
+	commitDir="$repoName/$stageDir"
+else 
+	commitDir="$repoName/$commitNum"
+fi
+
+# echo " ===> Commit direc: $commitDir"
+# echo " ===> File to show: $fileToShow"
+
+if ! test -e "$commitDir/$fileToShow"; then
+	echo "$0: error: '$fileToShow' not found in $commitDir"
+	exit 1
+fi
+
+cat "$commitDir/$fileToShow"
