give  Tue 14 Jul 11:49:25 AEST 2020: failing last 6 tests

diff --git a/shrug-checkout b/shrug-checkout
--- a/shrug-checkout
+++ b/shrug-checkout
@@ -6,6 +6,10 @@
 branchName=$1
 branchDir="$repoName/$branchName"
 
+# TODO: Terrible code
+latestBranchCommit=$(shrug-log | head -1 | cut -d' ' -f1)
+headFile="$repoName/$latestBranchCommit/$targetFile"
+
 cd "$repoName"
 
 if test "$(readlink $currBranch)" = $branchName; then
@@ -31,11 +35,50 @@ else
     # echo "$branchFiles"
 
 
-
     cd ..
+
+    # TODO: overwritten by checkout
+    willOverwrite=false
+
+
+    for eachFile in $(echo $stageFiles $cwdFiles $branchFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
+        cwdFile="$eachFile"
+        branchFile="$repoName/$branchName/$eachFile"
+        stageFile="$stageDir/$eachFile"
+        headFile="$headDir/$eachFile"
+
+        # If the file exists in target branch AND cwd BUT NOT in index, then
+        # replacing this file would overwrite uncommitted changes
+        if test -e "$branchFile" && test -e "$cwdFile" && ! test -e "$stageFile"; then
+            if test $willOverwrite = "false"; then
+                echo "$thisFile: error: Your changes to the following files would be overwritten by checkout:"
+                willOverwrite=true
+            fi
+            echo "$eachFile"
+        fi
+
+        # If the file doesn't exist in the target branch, checkout may deleted uncommitted
+        # work in the CWD file with the same name
+        if ! test -e "$branchFile" ; then
+
+            if shrug-alt-file-should-commit "$eachFile" > /dev/null; then
+                if test $willOverwrite = "false"; then
+                    echo "$thisFile: error: Your changes to the following files would be overwritten by checkout:"
+                    willOverwrite=true
+                fi
+                echo "$eachFile"
+            fi
+        fi
+    done
+
+    if test $willOverwrite = "true"; then
+        exit 1
+    fi
+
+    # For each file in either the stage, cwd or target branch
     for eachFile in $(echo $stageFiles $cwdFiles $branchFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
         if test -e "$repoName/$branchName/$eachFile"; then
-            if ! shrug-file-should-commit $eachFile  > /dev/null; then
+            if ! shrug-file-should-commit $eachFile > /dev/null; then
                 # echo " ===> REPLACING FILE $eachFile"
                 rm "$eachFile" 2> /dev/null
                 rm "$stageDir/$eachFile" 2> /dev/null
diff --git a/shrug-merge b/shrug-merge
--- a/shrug-merge
+++ b/shrug-merge
@@ -1,2 +1,61 @@
 #!/bin/dash
 
+. shrug-conf
+. shrug-exists
+
+# Getting the target branch
+targetBranch="$1"
+shift
+
+message=""
+while test $# -gt 0; do  # $# is the number of args
+    case "$1" in
+        -m)
+            # Extracting the commit message
+            shift
+            message=$1
+            shift
+            ;;
+        *)
+            exit 1
+            ;;
+    esac
+done
+if test -z "$message"; then
+    echo "$thisFile: error: empty commit message"
+    exit 1
+fi
+
+branchTipDir="$repoName/$targetBranch/"
+
+
+# Fast forward merge
+isFastForward=true
+if test isFastForward = "true"; then
+    # Remove all files in CWD, index and current branch
+    rm $(ls) 2> /dev/null
+    cd $stageDir
+    rm $(ls) 2> /dev/null
+    cd ../$currBranch
+    rm $(ls) 2> /dev/null
+    cd ../..
+
+    # Copy over every file in the target branch tip to CWD, index and current branch
+    for eachFile in $(ls $branchTipDir); do
+        cp "$branchTipDir/$eachFile" "$eachFile"
+        cp "$branchTipDir/$eachFile" "$stageDir/$eachFile"
+        cp "$branchTipDir/$eachFile" "$repoName/$currBranch/$eachFile"
+    done
+
+    # Update the log file of current branch
+    cp "$branchTipDir/.log" "$logFile"
+
+    echo "Fast-forward: no commit created"
+fi
+
+
+
+
+
+
+
