give  Tue  7 Jul 19:34:30 AEST 2020: done with subset 1's status and rm, first draft

diff --git a/shrug-rm b/shrug-rm
--- a/shrug-rm
+++ b/shrug-rm
@@ -1,21 +1,132 @@
 #!/bin/dash
 
+repoName=".shrug"
+stageDir="$repoName/index"
+cwd=$(pwd)  # TODO: Pwd won't work if run in diff directory...
+latestCommit=$(sh get-head)
+headDir="$repoName/$latestCommit"
+
+default=true
+force=false
+cached=false
 while test $# -gt 0; do  # $# is the number of args
     case "$1" in
         --force) 
+            default=false
+            force=true
             shift
             ;;
         --cached)
-            # Extract the commit message
+            default=false
+            cached=true
             shift
             ;;
         *)
-            echo "Filenames: $@"
-            exit 1
+            break
+            shift
             ;;
     esac
 done
 
-if test $# -lt 1; then
+if test $# -le 0; then
     echo "usage: $0 [--force] [--cached] <filenames>"
+    exit 1
 fi
+
+# echo "Filenames: $@"
+
+stageFiles=$(ls $stageDir)
+cwdFiles=$(ls $cwd)
+headFiles=$(ls $headDir)
+
+for eachFile in "$@"; do
+    stageFile="$stageDir/$eachFile"
+    headFile="$headDir/$eachFile"
+    currFile="$cwd/$eachFile"
+    # TODO: catch invalid filenames
+    # echo $currFile
+    # echo $stageFile
+    # echo $headFile
+
+    # All files exist
+    if test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
+        if test $default = true; then
+            if test -z "$(diff $currFile $stageFile)"; then
+                if test -z "$(diff $stageFile $headFile)"; then
+                    rm $currFile $stageFile
+                else 
+                    echo "$0: error: '$eachFile' has changes staged in the index"
+                fi
+            else
+                if test -z "$(diff $stageFile $headFile)"; then
+                    echo "$0: error: '$eachFile' in repository is different to working file"
+                else 
+                    echo "$0: error: '$eachFile' in index is different to both working file and repository"
+                fi
+            fi
+        elif test $cached = true && test $force = true; then
+            rm "$stageFile"
+        elif test $cached = true; then
+            if test -z "$(diff $currFile $stageFile)"; then
+                if test -z "$(diff $stageFile $headFile)"; then
+                    rm $stageFile
+                else 
+                    rm $stageFile
+                fi
+            else
+                if test -z "$(diff $stageFile $headFile)"; then
+                    rm $stageFile
+                else 
+                    echo "$0: error: '$eachFile' in index is different to both working file and repository"
+                fi
+            fi
+        elif test $force = true; then 
+            rm "$stageFile" "$currFile"
+        fi
+    # One file missing
+    elif test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
+        if test $default = true; then
+            if test -z "$(diff $currFile $stageFile)"; then
+                echo "$0: error: '$eachFile' has changes staged in the index"
+            else
+                echo "$0: error: '$eachFile' in index is different to both working file and repository"
+            fi
+        elif test $cached = true && test $force = true; then
+            rm "$stageFile"
+        elif test $cached = true; then
+            if test -z "$(diff $currFile $stageFile)"; then
+                rm "$stageFile"
+            else
+                rm $stageFile
+                echo "$0: error: '$eachFile' in index is different to both working file and repository"
+            fi
+        elif test $force = true; then 
+            rm "$stageFile" "$currFile"
+        fi
+    elif test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
+        echo "$0: error: '$eachFile' is not in the shrug repository"
+        exit 0
+    elif ! test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
+        rm $stageFile
+        exit 0
+    # Two files missing
+    elif test -e "$currFile" && ! test -e "$stageFile" && ! test -e "$headFile"; then
+        echo "$0: error: '$eachFile' is not in the shrug repository"
+        exit 0
+    elif ! test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
+        rm $stageFile
+        exit 0
+    elif ! test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
+        echo "$0: error: '$eachFile' is not in the shrug repository"
+        exit 0
+    elif ! test -e "$currFile" && ! test -e "$stageFile" && ! test -e "$headFile"; then
+        echo "$0: error: '$eachFile' is not in the shrug repository"
+        exit 0
+    fi
+done
+
+
+
+
+
+
diff --git a/shrug-show b/shrug-show
--- a/shrug-show
+++ b/shrug-show
@@ -4,18 +4,17 @@
 repoName=".shrug"
 stageDir="index"
 
-# Check if the repo exists
-if ! test -e "$repoName"; then
-    echo "$0: error: no .shrug directory containing shrug repository exists"
-    exit 1
-fi
+# Check if the repo exists (TODO? Is this right? this fails the autotest but I swear the reference does this)
+# if ! test -e "$repoName"; then
+#     echo "$0: error: no .shrug directory containing shrug repository exists"
+#     exit 1
+# fi
 
-
-# No commits in the repo
-if ! sh get-head > /dev/null; then
-	echo "$0: error: your repository does not have any commits yet"
-	exit 1
-fi
+# No commits in the repo (TODO?)
+# if ! sh get-head > /dev/null; then
+# 	echo "$0: error: your repository does not have any commits yet"
+# 	exit 1
+# fi
 
 # Incorrect usage
 if test "$#" -ne 1; then
diff --git a/shrug-status b/shrug-status
--- a/shrug-status
+++ b/shrug-status
@@ -2,6 +2,7 @@
 
 repoName=".shrug"
 stageDir="$repoName/index"
+cwd=$(pwd)
 latestCommit=$(sh get-head)
 headDir="$repoName/$latestCommit"
 
@@ -11,19 +12,68 @@ if ! test -e "$stageDir"; then
     exit 1
 fi
 
-for eachFile in $(ls $stageDir); do
+# Check if the repository has any commits (TODO is this right?)
+# if ! sh get-head; then
+#     echo "$0: error: your repository does not have any commits yet"
+#     exit 1
+# fi
+
+stageFiles=$(ls $stageDir)
+cwdFiles=$(ls $cwd)
+headFiles=$(ls $headDir)
+
+# TODO: String set?
+for eachFile in $(echo $stageFiles $cwdFiles $headFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
     stageFile="$stageDir/$eachFile"
     headFile="$headDir/$eachFile"
-    
-    if test -e "$headFile"; then
-        # If the file exists in both the head and the stage, check if they are identical
-        if test -z "$(diff $headFile $stageFile)"; then
-            echo "$eachFile - same as repo"
-        else 
-            echo "$eachFile - file changed, different changes staged for commit | changes staged for commit | changes not staged for commit"
+    currFile="$cwd/$eachFile"
+    # TODO: catch invalid filenames
+
+    # All files exist
+    # TODO FIX THIS
+    if test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
+        if test -z "$(diff $currFile $stageFile)"; then
+            if test -z "$(diff $stageFile $headFile)"; then
+                echo "$eachFile - same as repo"
+            else 
+                echo "$eachFile - file changed, changes staged for commit"
+            fi
+        else
+            if test -z "$(diff $stageFile $headFile)"; then
+                echo "$eachFile - file changed, changes not staged for commit"
+            else 
+                echo "$eachFile - file changed, different changes staged for commit"
+            fi
         fi
-    else
-        # The stage has a file which is not in the head. This means the commit should proceed
+    fi
+
+    # One file missing
+    if test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
+        if test -z "$(diff $currFile $stageFile)"; then
+            echo "$eachFile - added to index"
+        else
+            echo "$eachFile - added to index, file changed"
+        fi
+    fi
+
+    if test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
         echo "$eachFile - untracked"
+    fi
+
+    if ! test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
+        echo "$eachFile - file deleted"
+    fi
+
+    # Two files missing
+    if test -e "$currFile" && ! test -e "$stageFile" && ! test -e "$headFile"; then
+        echo "$eachFile - untracked"
+    fi
+
+    if ! test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
+        echo "$eachFile - added to index, file deleted"
+    fi
+
+    if ! test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
+        echo "$eachFile - deleted"
     fi
 done
