give  Sun  5 Jul 19:54:46 AEST 2020: made shrug-commit prepend to a log file in .shrug and added argument flag handling

diff --git a/shrug-add b/shrug-add
--- a/shrug-add
+++ b/shrug-add
@@ -5,7 +5,8 @@ stageDir="$repoName/.index"
 
 # Check if the repo exists
 if ! test -e "$repoName"; then
-    echo "$0: error: no $repoName directory containing shrug repository"
+    echo "$0: error: no $repoName directory containing shrug repository exists"
+    exit 1
 fi
 
 # Creating the index directory if it doesn't exist
@@ -15,17 +16,17 @@ fi
 
 for eachFile in "$@"; do
     if test -e "$eachFile"; then
-        echo " ===> Adding: $eachFile"
+        # echo " ===> Adding: $eachFile"
 
         # The filename already exists - ie. it was staged already.
-        if test -e "$stageDir/$eachFile"; then
-            echo "     ---> $eachFile already staged. Overwriting"
-        fi
+        # if test -e "$stageDir/$eachFile"; then
+            # echo "     ---> $eachFile already staged. Overwriting"
+        # fi
 
         cp "$eachFile" "$stageDir"
     else
         # Specified file does not exist in the current directory
-        echo "$0: error: invalid filename '$eachFile'"
+        echo "$0: error: can not open '$eachFile'"
         exit 1
     fi
 done
